name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLUTTER_VERSION: 3.10.1
  JAVA_VERSION: 11

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analyze Flutter code
        uses: ./.github/workflows/analyze-action
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test and generate coverage
        uses: ./.github/workflows/test-action
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
